version: '3'

services:
  mlflow:
    container_name: pytrade2-mlflow
    hostname: pytrade2-mlflow
    image: ghcr.io/mlflow/mlflow
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install boto3 &&
      mlflow server --host 0.0.0.0 --default-artifact-root s3://pytrade2/mlartifacts --artifacts-destination s3://pytrade2/mlartifacts"

    volumes:
      - ./mlruns:/mlruns