version: '3'

services:
  mlflow:
    container_name: pytrade2-mlflow
    hostname: pytrade2-mlflow
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server --serve-artifacts --host 0.0.0.0

    volumes:
      - ./../mlartifacts:/mlartifacts
      - ./../mlruns:/mlruns